// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package loader

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDetector returns the embedded CollectionSpec for detector.
func loadDetector() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DetectorBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load detector: %w", err)
	}

	return spec, err
}

// loadDetectorObjects loads detector and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*detectorObjects
//	*detectorPrograms
//	*detectorMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDetectorObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDetector()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// detectorSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type detectorSpecs struct {
	detectorProgramSpecs
	detectorMapSpecs
}

// detectorSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type detectorProgramSpecs struct {
	TraceExecve *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceSetgid *ebpf.ProgramSpec `ebpf:"trace_setgid"`
	TraceSetuid *ebpf.ProgramSpec `ebpf:"trace_setuid"`
}

// detectorMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type detectorMapSpecs struct {
	Events *ebpf.MapSpec `ebpf:"events"`
}

// detectorObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDetectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type detectorObjects struct {
	detectorPrograms
	detectorMaps
}

func (o *detectorObjects) Close() error {
	return _DetectorClose(
		&o.detectorPrograms,
		&o.detectorMaps,
	)
}

// detectorMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDetectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type detectorMaps struct {
	Events *ebpf.Map `ebpf:"events"`
}

func (m *detectorMaps) Close() error {
	return _DetectorClose(
		m.Events,
	)
}

// detectorPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDetectorObjects or ebpf.CollectionSpec.LoadAndAssign.
type detectorPrograms struct {
	TraceExecve *ebpf.Program `ebpf:"trace_execve"`
	TraceSetgid *ebpf.Program `ebpf:"trace_setgid"`
	TraceSetuid *ebpf.Program `ebpf:"trace_setuid"`
}

func (p *detectorPrograms) Close() error {
	return _DetectorClose(
		p.TraceExecve,
		p.TraceSetgid,
		p.TraceSetuid,
	)
}

func _DetectorClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed detector_bpfel_arm64.o
var _DetectorBytes []byte
